package models

type Transaction struct {
	User                         string      `json:"user,omitempty"`
	TransactionJournalId         string      `json:"transaction_journal_id,omitempty"`
	Date                         string      `json:"date,omitempty"`
	Order                        int         `json:"order,omitempty"`
	CurrencyId                   string      `json:"currency_id,omitempty"`
	CurrencyCode                 string      `json:"currency_code,omitempty"`
	CurrencySymbol               string      `json:"currency_symbol,omitempty"`
	CurrencyName                 string      `json:"currency_name,omitempty"`
	CurrencyDecimalPlaces        int         `json:"currency_decimal_places,omitempty"`
	ForeignCurrencyId            string      `json:"foreign_currency_id,omitempty"`
	ForeignCurrencyCode          string      `json:"foreign_currency_code,omitempty"`
	ForeignCurrencySymbol        string      `json:"foreign_currency_symbol,omitempty"`
	ForeignCurrencyDecimalPlaces int         `json:"foreign_currency_decimal_places,omitempty"`
	Amount                       string      `json:"amount,omitempty"`
	ForeignAmount                string      `json:"foreign_amount,omitempty"`
	Description                  string      `json:"description,omitempty"`
	SourceId                     string      `json:"source_id,omitempty"`
	SourceName                   string      `json:"source_name,omitempty"`
	SourceIBAN                   string      `json:"source_iban,omitempty"`
	SourceType                   string      `json:"source_type,omitempty"`
	DestinationId                string      `json:"destination_id,omitempty"`
	DestinationName              string      `json:"destination_name,omitempty"`
	DestinationIBAN              string      `json:"destination_iban,omitempty"`
	DestinationType              string      `json:"destination_type,omitempty"`
	BudgetId                     string      `json:"budget_id,omitempty"`
	BudgetName                   string      `json:"budget_name,omitempty"`
	CategoryId                   string      `json:"category_id,omitempty"`
	CategoryName                 string      `json:"category_name,omitempty"`
	BillId                       string      `json:"bill_id,omitempty"`
	BillName                     string      `json:"bill_name,omitempty"`
	Reconciled                   bool        `json:"reconciled,omitempty"`
	Notes                        string      `json:"notes,omitempty"`
	Tags                         interface{} `json:"tags,omitempty"`
	InternalReference            string      `json:"internal_reference,omitempty"`
	ExternalId                   string      `json:"external_id,omitempty"`
	ExternalUrl                  string      `json:"external_url,omitempty"`
	OriginalSource               string      `json:"original_source,omitempty"`
	RecurrenceId                 string      `json:"recurrence_id,omitempty"`
	RecurrenceTotal              int         `json:"recurrence_total,omitempty"`
	RecurrenceCount              int         `json:"recurrence_count,omitempty"`
	BunqPaymentId                string      `json:"bunq_payment_id,omitempty"`
	ImportHashV2                 string      `json:"import_hash_v2,omitempty"`
	SepaCC                       string      `json:"sepa_cc,omitempty"`
	SepaCTOP                     string      `json:"sepa_ct_op,omitempty"`
	SepaCTId                     string      `json:"sepa_ct_id,omitempty"`
	SepaDB                       string      `json:"sepa_db,omitempty"`
	SepaCountry                  string      `json:"sepa_country,omitempty"`
	SepaEP                       string      `json:"sepa_ep,omitempty"`
	SepaCI                       string      `json:"sepa_ci,omitempty"`
	SepaBatchId                  string      `json:"sepa_batch_id,omitempty"`
	InterestDate                 string      `json:"interest_date,omitempty"`
	BookDate                     string      `json:"book_date,omitempty"`
	ProcessDate                  string      `json:"process_date,omitempty"`
	DueDate                      string      `json:"due_date,omitempty"`
	PaymentDate                  string      `json:"payment_date,omitempty"`
	InvoiceDate                  string      `json:"invoice_date,omitempty"`
	Latitude                     float64     `json:"latitude,omitempty"`
	Longitude                    float64     `json:"longitude,omitempty"`
	ZoomLevel                    int         `json:"zoom_level,omitempty"`
	HasAttachments               bool        `json:"has_attachments,omitempty"`
}
